spring.application.name=toycatalog
spring.datasource.url=jdbc:mysql://localhost/toy_catalog
spring.datasource.username=root
spring.datasource.password=

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true